app:
    resource: "@AppBundle/Controller/"
    type:     annotation

yazi-ekle:
    path:     /yazi-ekle
    defaults: { _controller: AppBundle:Default:yaziEkle }

listele:
    path:     /listele
    defaults: { _controller: AppBundle:Default:yaziListele }

yazi:
    path:     /yazi/{slug}
    defaults: { _controller: AppBundle:Default:yazininTamami }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:adminSayfa }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"